.TH "F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Levels/GameMode.cs" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Levels/GameMode.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGemBlocks\fP"
.br
.ti -1c
.RI "namespace \fBGemBlocks\&.Levels\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGemBlocks\&.Levels\&.GameMode\fP { \fBGemBlocks\&.Levels\&.GameMode\&.Survival\fP = 0, \fBGemBlocks\&.Levels\&.GameMode\&.Creative\fP = 1, \fBGemBlocks\&.Levels\&.GameMode\&.Adventure\fP = 2, \fBGemBlocks\&.Levels\&.GameMode\&.Spectator\fP = 3 }"
.br
.RI "Gamemodes of Minecraft "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
