.TH "GemBlocks.Worlds.NibbleArray" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Worlds.NibbleArray \- An array for nibbles (4-bit values)  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNibbleArray\fP (int size)"
.br
.ti -1c
.RI "void \fBSet\fP (int index, byte value)"
.br
.RI "Sets an element "
.ti -1c
.RI "byte \fBGet\fP (int index)"
.br
.RI "Gets an element "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBSize\fP\fC [get]\fP"
.br
.RI "The number of elements "
.ti -1c
.RI "byte[] \fBBytes\fP\fC [get]\fP"
.br
.RI "Returns the byte array that holds the nibble values\&. In case the size of the nibble array is odd, the last bytes will only hold one nibble\&. "
.in -1c
.SH "Detailed Description"
.PP 
An array for nibbles (4-bit values) 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "GemBlocks\&.Worlds\&.NibbleArray\&.NibbleArray (int size)"

.SH "Member Function Documentation"
.PP 
.SS "byte GemBlocks\&.Worlds\&.NibbleArray\&.Get (int index)"

.PP
Gets an element 
.SS "void GemBlocks\&.Worlds\&.NibbleArray\&.Set (int index, byte value)"

.PP
Sets an element 
.SH "Property Documentation"
.PP 
.SS "byte [] GemBlocks\&.Worlds\&.NibbleArray\&.Bytes\fC [get]\fP"

.PP
Returns the byte array that holds the nibble values\&. In case the size of the nibble array is odd, the last bytes will only hold one nibble\&. 
.SS "int GemBlocks\&.Worlds\&.NibbleArray\&.Size\fC [get]\fP"

.PP
The number of elements 

.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
