.TH "GemBlocks.Worlds" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Worlds
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChunk\fP"
.br
.RI "Defines a chunk\&. It consists of 16x16 blocks in XZ-dimension and up to 16 sections for the height\&. "
.ti -1c
.RI "class \fBDefaultLayers\fP"
.br
.RI "Can be used to define the default block layers of the part of the world that was created by \fBGemBlocks\fP\&. This results in a flat world where the blocks of each Y-coordinate are the same until they get overwritten\&. It is recommended to combine the \fBDefaultLayers\fP with the FlatGenerator to get a consitent world\&. "
.ti -1c
.RI "interface \fBIBlockContainer\fP"
.br
.ti -1c
.RI "class \fBNibbleArray\fP"
.br
.RI "An array for nibbles (4-bit values) "
.ti -1c
.RI "class \fBPosition\fP"
.br
.ti -1c
.RI "class \fBRegion\fP"
.br
.ti -1c
.RI "class \fBSection\fP"
.br
.RI "Defines a section\&. It consists of 16 blocks in each dimension\&. "
.ti -1c
.RI "class \fBWorld\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
