.TH "GemBlocks.Levels.Generators.IGenerator" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Levels.Generators.IGenerator \- Inteface for world generators\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGemBlocks\&.Levels\&.Generators\&.FlatGenerator\fP, and \fBGemBlocks\&.Levels\&.Generators\&.SimpleGenerator\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.RI "The generator name as it is used in the level file\&. "
.ti -1c
.RI "string \fBOptions\fP\fC [get]\fP"
.br
.RI "The generator options as they are used in the level file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Inteface for world generators\&. 


.SH "Property Documentation"
.PP 
.SS "string GemBlocks\&.Levels\&.Generators\&.IGenerator\&.Name\fC [get]\fP"

.PP
The generator name as it is used in the level file\&. 
.SS "string GemBlocks\&.Levels\&.Generators\&.IGenerator\&.Options\fC [get]\fP"

.PP
The generator options as they are used in the level file\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
