.TH "GemBlocks.Levels.Generators.FlatGenerator" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Levels.Generators.FlatGenerator \- Generates a super-flat world  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGemBlocks\&.Levels\&.Generators\&.IGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlatGenerator\fP ()"
.br
.RI "Unused? "
.ti -1c
.RI "\fBFlatGenerator\fP (\fBDefaultLayers\fP layers)"
.br
.RI "Loads this instance with the desired layers "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBName\fP => 'flat'"
.br
.RI "Used by the world generator "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBOptions\fP\fC [get]\fP"
.br
.RI "Used by the world generator "
.in -1c
.SH "Detailed Description"
.PP 
Generates a super-flat world 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "GemBlocks\&.Levels\&.Generators\&.FlatGenerator\&.FlatGenerator ()"

.PP
Unused? 
.SS "GemBlocks\&.Levels\&.Generators\&.FlatGenerator\&.FlatGenerator (\fBDefaultLayers\fP layers)"

.PP
Loads this instance with the desired layers 
.PP
\fBParameters\fP
.RS 4
\fIlayers\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "string GemBlocks\&.Levels\&.Generators\&.FlatGenerator\&.Name => 'flat'"

.PP
Used by the world generator 
.SH "Property Documentation"
.PP 
.SS "string GemBlocks\&.Levels\&.Generators\&.FlatGenerator\&.Options\fC [get]\fP"

.PP
Used by the world generator 

.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
