.TH "GemBlocks.Tags.ITagProvider" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Tags.ITagProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGemBlocks\&.Levels\&.Level\fP, \fBGemBlocks\&.Tags\&.CompoundTagFactory\fP, \fBGemBlocks\&.Tags\&.ListTagFactory\fP, \fBGemBlocks\&.Worlds\&.Chunk\fP, and \fBGemBlocks\&.Worlds\&.Section\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "Tag \fBTag\fP\fC [get]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "Tag GemBlocks\&.Tags\&.ITagProvider\&.Tag\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
