.TH "GemBlocks.Tags.CompoundTagFactory" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Tags.CompoundTagFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGemBlocks\&.Tags\&.ITagProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompoundTagFactory\fP (string name)"
.br
.ti -1c
.RI "void \fBSet\fP (\fBTag\fP tag)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Tag \fBTag\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GemBlocks\&.Tags\&.CompoundTagFactory\&.CompoundTagFactory (string name)"

.SH "Member Function Documentation"
.PP 
.SS "void GemBlocks\&.Tags\&.CompoundTagFactory\&.Set (\fBTag\fP tag)"

.SH "Property Documentation"
.PP 
.SS "Tag GemBlocks\&.Tags\&.CompoundTagFactory\&.Tag\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
