.TH "GemBlocks.Worlds.IBlockContainer" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Worlds.IBlockContainer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGemBlocks\&.Worlds\&.Chunk\fP, \fBGemBlocks\&.Worlds\&.Region\fP, \fBGemBlocks\&.Worlds\&.Section\fP, and \fBGemBlocks\&.Worlds\&.World\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "byte \fBGetSkyLight\fP (\fBPosition\fP pos)"
.br
.RI "Returns the sky light level of the block at given positon\&. If there is no block \fBWorld\&.DefaultSkyLight\fP will be returned\&. "
.ti -1c
.RI "byte \fBGetSkyLightFromParent\fP (\fBIBlockContainer\fP childBlock, \fBPosition\fP child)"
.br
.RI "Returns the sky light level of a block that is out of bounds of the child block container\&. "
.ti -1c
.RI "void \fBSpreadSkyLight\fP (byte light)"
.br
.RI "Spreads the sky light\&. For each block that has the given light level it's adjacent blocks will be lit if their current light level is lower\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "byte GemBlocks\&.Worlds\&.IBlockContainer\&.GetSkyLight (\fBPosition\fP pos)"

.PP
Returns the sky light level of the block at given positon\&. If there is no block \fBWorld\&.DefaultSkyLight\fP will be returned\&. 
.PP
\fBParameters\fP
.RS 4
\fIpos\fP The local XYZ-coordinate
.RE
.PP
\fBReturns\fP
.RS 4
The sky light level
.RE
.PP

.PP
Implemented in \fBGemBlocks\&.Worlds\&.Section\fP, \fBGemBlocks\&.Worlds\&.Chunk\fP, \fBGemBlocks\&.Worlds\&.World\fP, and \fBGemBlocks\&.Worlds\&.Region\fP\&.
.SS "byte GemBlocks\&.Worlds\&.IBlockContainer\&.GetSkyLightFromParent (\fBIBlockContainer\fP childBlock, \fBPosition\fP child)"

.PP
Returns the sky light level of a block that is out of bounds of the child block container\&. 
.PP
\fBParameters\fP
.RS 4
\fIchildBlock\fP The child block container
.br
\fIchild\fP The local X,Y, & Z coordinate
.RE
.PP
\fBReturns\fP
.RS 4
The sky light level
.RE
.PP

.PP
Implemented in \fBGemBlocks\&.Worlds\&.Section\fP, \fBGemBlocks\&.Worlds\&.World\fP, \fBGemBlocks\&.Worlds\&.Region\fP, and \fBGemBlocks\&.Worlds\&.Chunk\fP\&.
.SS "void GemBlocks\&.Worlds\&.IBlockContainer\&.SpreadSkyLight (byte light)"

.PP
Spreads the sky light\&. For each block that has the given light level it's adjacent blocks will be lit if their current light level is lower\&. 
.PP
\fBParameters\fP
.RS 4
\fIlight\fP The light level
.RE
.PP

.PP
Implemented in \fBGemBlocks\&.Worlds\&.Chunk\fP, \fBGemBlocks\&.Worlds\&.Section\fP, \fBGemBlocks\&.Worlds\&.World\fP, and \fBGemBlocks\&.Worlds\&.Region\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
