.TH "GemBlocks.Levels.Level" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Levels.Level \- The level defines the settings for the world\&. i\&.e\&. Game Mode, spawn point, etc\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGemBlocks\&.Tags\&.ITagProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevel\fP (string levelName)"
.br
.RI "Initializes this instance, with Flat World "
.ti -1c
.RI "\fBLevel\fP (string levelName, \fBIGenerator\fP generator)"
.br
.RI "Initializes this instance "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.RI "The name of the level "
.ti -1c
.RI "bool \fBAllowCommands\fP\fC [get, set]\fP"
.br
.RI "Cheats enabled "
.ti -1c
.RI "bool \fBMapFeatures\fP\fC [get, set]\fP"
.br
.RI "Structures enabled "
.ti -1c
.RI "\fBGameMode\fP \fBGameMode\fP\fC [get, set]\fP"
.br
.RI "The gamemode of the world "
.ti -1c
.RI "\fBPosition\fP \fBSpawnPoint\fP\fC [get, set]\fP"
.br
.RI "Where new players spawn "
.ti -1c
.RI "long \fBRandomSeed\fP\fC [get, set]\fP"
.br
.RI "The seed of my fruitfulness "
.ti -1c
.RI "Tag?? \fBTag\fP\fC [get]\fP"
.br
.RI "Gets the NBT Tag "
.in -1c
.SH "Detailed Description"
.PP 
The level defines the settings for the world\&. i\&.e\&. Game Mode, spawn point, etc\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "GemBlocks\&.Levels\&.Level\&.Level (string levelName)"

.PP
Initializes this instance, with Flat World 
.PP
\fBParameters\fP
.RS 4
\fIlevelName\fP 
.RE
.PP

.SS "GemBlocks\&.Levels\&.Level\&.Level (string levelName, \fBIGenerator\fP generator)"

.PP
Initializes this instance 
.PP
\fBParameters\fP
.RS 4
\fIlevelName\fP 
.br
\fIgenerator\fP 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "bool GemBlocks\&.Levels\&.Level\&.AllowCommands\fC [get]\fP, \fC [set]\fP"

.PP
Cheats enabled 
.SS "\fBGameMode\fP GemBlocks\&.Levels\&.Level\&.GameMode\fC [get]\fP, \fC [set]\fP"

.PP
The gamemode of the world 
.SS "bool GemBlocks\&.Levels\&.Level\&.MapFeatures\fC [get]\fP, \fC [set]\fP"

.PP
Structures enabled 
.SS "string GemBlocks\&.Levels\&.Level\&.Name\fC [get]\fP"

.PP
The name of the level 
.SS "long GemBlocks\&.Levels\&.Level\&.RandomSeed\fC [get]\fP, \fC [set]\fP"

.PP
The seed of my fruitfulness 
.SS "\fBPosition\fP GemBlocks\&.Levels\&.Level\&.SpawnPoint\fC [get]\fP, \fC [set]\fP"

.PP
Where new players spawn 
.SS "Tag?? GemBlocks\&.Levels\&.Level\&.Tag\fC [get]\fP"

.PP
Gets the NBT Tag 

.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
