.TH "GemBlocks.Blocks.BlockRegistry" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Blocks.BlockRegistry
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBLoad\fP ()"
.br
.RI "Loads all the blocks into the registry\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static List< \fBBlock\fP > \fBBlocks\fP = new List<\fBBlock\fP>()"
.br
.RI "A list of all the static blocks in \fBBlock\&.cs\fP "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void GemBlocks\&.Blocks\&.BlockRegistry\&.Load ()\fC [static]\fP"

.PP
Loads all the blocks into the registry\&. 
.SH "Member Data Documentation"
.PP 
.SS "List<\fBBlock\fP> GemBlocks\&.Blocks\&.BlockRegistry\&.Blocks = new List<\fBBlock\fP>()\fC [static]\fP"

.PP
A list of all the static blocks in \fBBlock\&.cs\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
