.TH "GemBlocks.Tags" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Tags
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompoundTagFactory\fP"
.br
.ti -1c
.RI "interface \fBITagProvider\fP"
.br
.ti -1c
.RI "class \fBListTagFactory\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
