.TH "GemBlocks.Worlds.Position" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Worlds.Position
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPosition\fP (int x, int y, int z)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBX\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBY\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBZ\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GemBlocks\&.Worlds\&.Position\&.Position (int x, int y, int z)"

.SH "Property Documentation"
.PP 
.SS "int GemBlocks\&.Worlds\&.Position\&.X\fC [get]\fP, \fC [set]\fP"

.SS "int GemBlocks\&.Worlds\&.Position\&.Y\fC [get]\fP, \fC [set]\fP"

.SS "int GemBlocks\&.Worlds\&.Position\&.Z\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
