.TH "GemBlocks.Utils.RectArray< T >" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Utils.RectArray< T > \- A class to work around T[][]  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEnumerable< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "T[][] \fBToArray\fP ()"
.br
.ti -1c
.RI "void \fBSet\fP (int index, int index2, T value)"
.br
.ti -1c
.RI "T \fBGet\fP (int index, int index2)"
.br
.ti -1c
.RI "void \fBAdd\fP (T[] value)"
.br
.ti -1c
.RI "T[][] \fBAll\fP (int size1, int size2)"
.br
.ti -1c
.RI "IEnumerator< T > \fBGetEnumerator\fP ()"
.br
.ti -1c
.RI "\fBRectArray\fP ()"
.br
.ti -1c
.RI "\fBRectArray\fP (T[][] arr)"
.br
.ti -1c
.RI "\fBRectArray\fP (int size1, int size2)"
.br
.ti -1c
.RI "T[,] \fBToMultiDimArray\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBoperator RectArray< T >\fP (T[][] tVal)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T[][] \fBArray\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to work around T[][] 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.\fBRectArray\fP ()"

.SS "\fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.\fBRectArray\fP (T arr[][])"

.SS "\fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.\fBRectArray\fP (int size1, int size2)"

.SH "Member Function Documentation"
.PP 
.SS "void \fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.Add (T[] value)"

.SS "T [][] \fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.All (int size1, int size2)"

.SS "T \fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.Get (int index, int index2)"

.SS "IEnumerator<T> \fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.GetEnumerator ()"

.SS "static \fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.operator \fBRectArray\fP< T > (T tVal[][])\fC [explicit]\fP, \fC [static]\fP"

.SS "void \fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.Set (int index, int index2, T value)"

.SS "T [][] \fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.ToArray ()"

.SS "T [,] \fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.ToMultiDimArray ()"

.SH "Member Data Documentation"
.PP 
.SS "T [][] \fBGemBlocks\&.Utils\&.RectArray\fP< T >\&.Array"


.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
