.TH "GemBlocks.Levels" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Levels
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGenerators\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLevel\fP"
.br
.RI "The level defines the settings for the world\&. i\&.e\&. Game Mode, spawn point, etc\&. "
.ti -1c
.RI "class \fBWorldKinds\fP"
.br
.RI "The kind of normal world "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGameMode\fP { \fBGameMode\&.Survival\fP = 0, \fBGameMode\&.Creative\fP = 1, \fBGameMode\&.Adventure\fP = 2, \fBGameMode\&.Spectator\fP = 3 }"
.br
.RI "Gamemodes of Minecraft "
.ti -1c
.RI "enum \fBWorldType\fP { \fBWorldType\&.Default\fP, \fBWorldType\&.Amplified\fP, \fBWorldType\&.LargeBiomes\fP }"
.br
.RI "World kind? "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBGemBlocks\&.Levels\&.GameMode\fP\fC [strong]\fP"

.PP
Gamemodes of Minecraft 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISurvival \fP\fP
The default gamemode, where you must survive by retrieving materials and food to grow and build\&. 
.TP
\fB\fICreative \fP\fP
Free-roam, flying abilities, easy place and delete 
.TP
\fB\fIAdventure \fP\fP
Story time 
.TP
\fB\fISpectator \fP\fP
? 
.SS "enum \fBGemBlocks\&.Levels\&.WorldType\fP\fC [strong]\fP"

.PP
World kind? 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDefault \fP\fP
.TP
\fB\fIAmplified \fP\fP
.TP
\fB\fILargeBiomes \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
