.TH "GemBlocks.Levels.Generators.SimpleGenerator" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Levels.Generators.SimpleGenerator \- Generates the normal world types (Default, Amplified, Large Biomes)  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGemBlocks\&.Levels\&.Generators\&.IGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSimpleGenerator\fP (string value)"
.br
.RI "Initializes this instance with the specified world kind "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBName\fP => GetWorldKindString()"
.br
.RI "Tells the world generator what kind of world "
.ti -1c
.RI "string \fBOptions\fP => null"
.br
.RI "Options\&.\&.\&.\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBWorldType\fP \fBWorldKind\fP\fC [get, set]\fP"
.br
.RI "The kind of world "
.in -1c
.SH "Detailed Description"
.PP 
Generates the normal world types (Default, Amplified, Large Biomes) 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "GemBlocks\&.Levels\&.Generators\&.SimpleGenerator\&.SimpleGenerator (string value)"

.PP
Initializes this instance with the specified world kind 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "string GemBlocks\&.Levels\&.Generators\&.SimpleGenerator\&.Name => GetWorldKindString()"

.PP
Tells the world generator what kind of world 
.SS "string GemBlocks\&.Levels\&.Generators\&.SimpleGenerator\&.Options => null"

.PP
Options\&.\&.\&.\&. 
.SH "Property Documentation"
.PP 
.SS "\fBWorldType\fP GemBlocks\&.Levels\&.Generators\&.SimpleGenerator\&.WorldKind\fC [get]\fP, \fC [set]\fP"

.PP
The kind of world 

.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
