.TH "GemBlocks.Levels.Generators" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Levels.Generators
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFlatGenerator\fP"
.br
.RI "Generates a super-flat world "
.ti -1c
.RI "interface \fBIGenerator\fP"
.br
.RI "Inteface for world generators\&. "
.ti -1c
.RI "class \fBSimpleGenerator\fP"
.br
.RI "Generates the normal world types (Default, Amplified, Large Biomes) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
