.TH "GemBlocks.Blocks.States" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Blocks.States
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFacing2State\fP { \fBFacing2State\&.NorthSouth\fP, \fBFacing2State\&.EastWest\fP }"
.br
.ti -1c
.RI "enum \fBFacing4State\fP { \fBFacing4State\&.North\fP, \fBFacing4State\&.South\fP, \fBFacing4State\&.East\fP, \fBFacing4State\&.West\fP }"
.br
.ti -1c
.RI "enum \fBFacing5State\fP { \fBFacing5State\&.North\fP, \fBFacing5State\&.South\fP, \fBFacing5State\&.East\fP, \fBFacing5State\&.West\fP, \fBFacing5State\&.Up\fP }"
.br
.ti -1c
.RI "enum \fBHalfState\fP { \fBHalfState\&.Upper\fP, \fBHalfState\&.Lower\fP }"
.br
.ti -1c
.RI "enum \fBWoodState\fP { \fBWoodState\&.Oak\fP, \fBWoodState\&.Spruce\fP, \fBWoodState\&.Birch\fP, \fBWoodState\&.Jungle\fP, \fBWoodState\&.Acacia\fP, \fBWoodState\&.DarkOak\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBGemBlocks\&.Blocks\&.States\&.Facing2State\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINorthSouth \fP\fP
.TP
\fB\fIEastWest \fP\fP
.SS "enum \fBGemBlocks\&.Blocks\&.States\&.Facing4State\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINorth \fP\fP
.TP
\fB\fISouth \fP\fP
.TP
\fB\fIEast \fP\fP
.TP
\fB\fIWest \fP\fP
.SS "enum \fBGemBlocks\&.Blocks\&.States\&.Facing5State\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINorth \fP\fP
.TP
\fB\fISouth \fP\fP
.TP
\fB\fIEast \fP\fP
.TP
\fB\fIWest \fP\fP
.TP
\fB\fIUp \fP\fP
.SS "enum \fBGemBlocks\&.Blocks\&.States\&.HalfState\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUpper \fP\fP
.TP
\fB\fILower \fP\fP
.SS "enum \fBGemBlocks\&.Blocks\&.States\&.WoodState\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOak \fP\fP
.TP
\fB\fISpruce \fP\fP
.TP
\fB\fIBirch \fP\fP
.TP
\fB\fIJungle \fP\fP
.TP
\fB\fIAcacia \fP\fP
.TP
\fB\fIDarkOak \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
