.TH "GemBlocks.Worlds.Region" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GemBlocks.Worlds.Region
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGemBlocks\&.Worlds\&.IBlockContainer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegion\fP (\fBIBlockContainer\fP parent, int xPos, int zPos, \fBDefaultLayers\fP layers)"
.br
.ti -1c
.RI "void \fBSetBlock\fP (\fBPosition\fP pos, \fBBlock\fP block)"
.br
.ti -1c
.RI "byte \fBGetSkyLight\fP (\fBPosition\fP pos)"
.br
.RI "Returns the sky light level of the block at given positon\&. If there is no block \fBWorld\&.DefaultSkyLight\fP will be returned\&. "
.ti -1c
.RI "byte \fBGetSkyLightFromParent\fP (\fBIBlockContainer\fP blockChild, \fBPosition\fP child)"
.br
.RI "Returns the sky light level of a block that is out of bounds of the child block container\&. "
.ti -1c
.RI "void \fBSpreadSkyLight\fP (byte light)"
.br
.RI "Spreads the sky light\&. For each block that has the given light level it's adjacent blocks will be lit if their current light level is lower\&. "
.ti -1c
.RI "void \fBAddSkyLight\fP ()"
.br
.ti -1c
.RI "int \fBGetHighestBlock\fP (int x, int z)"
.br
.ti -1c
.RI "void \fBCalculateHeightMap\fP ()"
.br
.ti -1c
.RI "void \fBWriteToFile\fP (File path)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBChunksPerRegionSide\fP = 32"
.br
.ti -1c
.RI "const int \fBBlocksPerRegionSize\fP = \fBChunksPerRegionSide\fP * \fBChunk\&.BlocksPerChunkSide\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBX\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBZ\fP\fC [get]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GemBlocks\&.Worlds\&.Region\&.Region (\fBIBlockContainer\fP parent, int xPos, int zPos, \fBDefaultLayers\fP layers)"

.SH "Member Function Documentation"
.PP 
.SS "void GemBlocks\&.Worlds\&.Region\&.AddSkyLight ()"

.SS "void GemBlocks\&.Worlds\&.Region\&.CalculateHeightMap ()"

.SS "int GemBlocks\&.Worlds\&.Region\&.GetHighestBlock (int x, int z)"

.SS "byte GemBlocks\&.Worlds\&.Region\&.GetSkyLight (\fBPosition\fP pos)"

.PP
Returns the sky light level of the block at given positon\&. If there is no block \fBWorld\&.DefaultSkyLight\fP will be returned\&. 
.PP
\fBParameters\fP
.RS 4
\fIpos\fP The local XYZ-coordinate
.RE
.PP
\fBReturns\fP
.RS 4
The sky light level
.RE
.PP

.PP
Implements \fBGemBlocks\&.Worlds\&.IBlockContainer\fP\&.
.SS "byte GemBlocks\&.Worlds\&.Region\&.GetSkyLightFromParent (\fBIBlockContainer\fP childBlock, \fBPosition\fP child)"

.PP
Returns the sky light level of a block that is out of bounds of the child block container\&. 
.PP
\fBParameters\fP
.RS 4
\fIchildBlock\fP The child block container
.br
\fIchild\fP The local X,Y, & Z coordinate
.RE
.PP
\fBReturns\fP
.RS 4
The sky light level
.RE
.PP

.PP
Implements \fBGemBlocks\&.Worlds\&.IBlockContainer\fP\&.
.SS "void GemBlocks\&.Worlds\&.Region\&.SetBlock (\fBPosition\fP pos, \fBBlock\fP block)"

.SS "void GemBlocks\&.Worlds\&.Region\&.SpreadSkyLight (byte light)"

.PP
Spreads the sky light\&. For each block that has the given light level it's adjacent blocks will be lit if their current light level is lower\&. 
.PP
\fBParameters\fP
.RS 4
\fIlight\fP The light level
.RE
.PP

.PP
Implements \fBGemBlocks\&.Worlds\&.IBlockContainer\fP\&.
.SS "void GemBlocks\&.Worlds\&.Region\&.WriteToFile (File path)"

.SH "Member Data Documentation"
.PP 
.SS "const int GemBlocks\&.Worlds\&.Region\&.BlocksPerRegionSize = \fBChunksPerRegionSide\fP * \fBChunk\&.BlocksPerChunkSide\fP\fC [static]\fP"

.SS "const int GemBlocks\&.Worlds\&.Region\&.ChunksPerRegionSide = 32\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "int GemBlocks\&.Worlds\&.Region\&.X\fC [get]\fP"

.SS "int GemBlocks\&.Worlds\&.Region\&.Z\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
