.TH "F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Blocks/States/HalfState.cs" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Blocks/States/HalfState.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGemBlocks\fP"
.br
.ti -1c
.RI "namespace \fBGemBlocks\&.Blocks\fP"
.br
.ti -1c
.RI "namespace \fBGemBlocks\&.Blocks\&.States\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGemBlocks\&.Blocks\&.States\&.HalfState\fP { \fBGemBlocks\&.Blocks\&.States\&.HalfState\&.Upper\fP, \fBGemBlocks\&.Blocks\&.States\&.HalfState\&.Lower\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
