.TH "F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Levels/Generators/IGenerator.cs" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Levels/Generators/IGenerator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBGemBlocks\&.Levels\&.Generators\&.IGenerator\fP"
.br
.RI "Inteface for world generators\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGemBlocks\fP"
.br
.ti -1c
.RI "namespace \fBGemBlocks\&.Levels\fP"
.br
.ti -1c
.RI "namespace \fBGemBlocks\&.Levels\&.Generators\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
