.TH "F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Levels/Level.cs" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Levels/Level.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGemBlocks\&.Levels\&.Level\fP"
.br
.RI "The level defines the settings for the world\&. i\&.e\&. Game Mode, spawn point, etc\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGemBlocks\fP"
.br
.ti -1c
.RI "namespace \fBGemBlocks\&.Levels\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBMath\fP = java\&.lang\&.Math"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBMath\fP =  java\&.lang\&.Math"

.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
