.TH "F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Utils/RectArray.cs" 3 "Thu Dec 19 2019" "GemBlocks" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Documents/Programming/GemsCraft/GemBlocks/GemBlocks/GemBlocks/Utils/RectArray.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGemBlocks\&.Utils\&.RectArray< T >\fP"
.br
.RI "A class to work around T[][] "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGemBlocks\fP"
.br
.ti -1c
.RI "namespace \fBGemBlocks\&.Utils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GemBlocks from the source code\&.
